version: "3.9"
services:
  watcher:
    image: ghcr.io/skip-mev/governor:latest
    ports:
      - "8000:8000"
    volumes:
      - "data:/opt/data/"
      - "./config.yaml:/opt/config.yaml"

volumes:
  data:
