version: "3.9"
services:
  watcher:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "data:/opt/data/"
      - "./config.yaml:/opt/config.yaml"
    environment:
      - "PROMETHEUS_MULTIPROC_DIR=/tmp/upgrade_watcher_prom"

volumes:
  data:
